### PR TITLE
Docs update

### LINKED ISSUE #421: Docs update!
New entity list commands + !shaped-abilities stuff + config options

### PR DESCRIPTION
**Pull request by liquidox**
Ok took some time to learn a bit of Git (been postponing that for some years...).

Could not get Gulp to work yet: http://pastebin.com/raw/H6w4wFEK
And the PR includes files I did not change myself, is this correct? (changelog, etc.). Please check carefully...

Should (mostly?) close #421

### CODE REVIEW

**Comment by liquidox** [comment]
Ah darn, not sure how yet. 
I tried " git reset --hard HEAD~1" but then I cannot "git push", kinda stuck there.

Or should I just edit and add a new commit?

**Comment by symposion** [comment]
You're very close! The only thing you now have to do is git push --force - because you've made a breaking revision to the branch that would break downstream repositories if they'd based commits off your previous HEAD. git push --force should be approached with extreme caution, but in this case, no one else other than this PR depends on the previous state of HEAD, so it's a reasonable thing to do in the name of keeping a clean history!

**Comment by symposion** [comment]
PS I'm impressed with how fast you're picking up git! If you're just learning now, you're at the stage where most people go "duh-wat????" But then maybe you've used another similar distributed VCS so it's not so alien. I remember I was totally baffled for months after switching from SVN!

**Comment by liquidox** [comment]
Hah thanks. No actually have not used SVN either. Our company uses SVN but I don't use it, am more systems/management.  But have wanted to learn Git, if only for personal use and perhaps to some day convince people that we need to switch to Git ;)

**Comment by symposion** [comment]
This is merged now, but thanks to Github's lack of support for rebasing PRs, I can't mark it as merged in the UI. But it is accepted. Thanks for taking the time to do this!

**Pull request closed without merging**
