### PR TITLE
Do not link NPC HP

### PR DESCRIPTION
**Pull request by liquidox**
Added configurable option to not link NPC HP.

### CODE REVIEW

**Comment by liquidox** [comment]
Hope I did it correctly now!

**Comment by symposion** [comment]
Pretty close! Thanks, this is a useful addition - sorry I didn't get to it myself early. Two things that I've changed which will help you if you want to send future PRs:
1. I forgot to mention - can you send PRs against the "develop" branch rather than master. I don't ever edit master directly - it gets built by Travis CI automatically when I decide to do a release.
2. When you want to add a config property you should do it using a migration rather than editing the oneSixConfig variable (which was the configuration state at the point that I introduced the migrations system). If you scroll down from where you edited shaped-config.js, you will see a long chain of calls like
```javascript
.nextVersion()
.addProperty('config.tokenSettings.blah', 'defaultValue')
.deleteProperty('other.property')
.nextVersion()
.moveProperty('config.tokenSettings.blah', 'config.tokenSettings.blort')
```
When you want to add a new property to the config, you should add a `nextVersion()` call to the bottom of that chain, followed by whatever edit operations you want to make to the configuration. This ensures that existing configurations get updated cleanly. It's not *strictly* necessary for the purely additive changes, but it keeps everything self-documenting and prevents oddness due to mismatched config versions.

**Comment by symposion** [comment]
Oh... and one other small piece of advice - I'd recommend (learned the hard way!) that you submit PRs from a branch yourself - because otherwise you can get yourself into a bit of a merge mess when I update stuff at my end. I'd suggest:

1. Make a branch off develop for your new feature/bugfix, and work on that
2. Right before you submit the PR, you can fetch upstream/develop, 
3.Do a fast-forward merge of upstream/develop into your develop branch (you'll never be editing develop directly),
4. Rebase your feature branch onto your newly updated develop. You can do an interactive rebase at this point to squash any WIP commits
5. Then submit your PR, which will be cleanly up-to-date with my latest code without any messy merge commits etc

If you run the default gulp task before you submit the PR (`gulp` on the command line, or the `default` task if you're running in a gulp-aware IDE), it will run the unit tests + also eslint to make sure you conform to the style guidelines.

**Comment by liquidox** [comment]
I think I ended up doing the following, it worked but not sure if correct...

1. git checkout -b develop origin/develop
2. git checkout -b doc_update origin/develop
3. Add my edits and stage + commit them.
4. git checkout develop
5. git fetch upstream
6. git merge upstream/develop
7. git rebase doc_update

**Comment by symposion** [comment]
That's pretty much it, but unless you've missed out some steps you took at the end, I think the last piece might be a little backwards. What you've done in the final steps above is to rebase develop onto your doc_update branch - whereas I think you wanted to do it the other way around. I would normally accomplish that by doing:
7. git checkout doc_update
8. git rebase develop
and then submit doc_update as the branch for your PR.
That probably explains how you've end up with those two extra commits in there.

**Comment by liquidox** [comment]
Ahh yes that explains!

**Pull request merged**
